# nothing

name: Today Status Check
# daily job
on:
  push:
  workflow_dispatch:
  schedule:
    - # daily job at 01:00 with  UTC time
      cron: "0 1 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    env:
      FNG_MIN: ${{ secrets.FNG_MIN }}
      FNG_MAX: ${{ secrets.FNG_MAX }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup Git Infomation
        run: |
          git config --global user.name 'bot'
          git config --global user.email 'robotTest@github.com'
      - name: Recording
        run: |
          npm install --global yarn && yarn install
          node .