# nothing

name: Today Status Check
# daily job
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "40 13 * * 1-5"
    - cron: "30 14 * * 1-5"
    - cron: "30 15 * * 1-5"
    - cron: "15 16 * * 1-5"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    env:
      FNG_MIN: ${{ secrets.FNG_MIN }}
      FNG_MAX: ${{ secrets.FNG_MAX }}
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      EMAIL_FROM: ${{ secrets.EMAIL_FROM }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/keepalive-workflow@v2 # using the workflow with default settings
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Preparing
        run: |
          npm install --global yarn && yarn install
      - name: Execute
        run: |
          node .

